### ISSUE TITLE
Register for opening in “Open with…” dialog (Linux/Flatpak)

### ISSUE THREAD

**Issue by Jak2k** [kra-mo/sly#46] opened 2024-12-15 12:58 UTC
![Screenshot From 2024-12-15 13-58-01](https://github.com/user-attachments/assets/4337fcdf-3295-437b-95d4-1a0340897340)

**Comment by kra-mo** [comment] 2024-12-15 14:01
Duplicate of #27

**Closed by kra-mo** 2024-12-15 14:01 UTC
