### ISSUE TITLE
 ARM/AArch64 builds for Linux

### ISSUE THREAD

**Issue by RasheedAZ** [kra-mo/sly#35] opened 2024-10-03 05:58 UTC
Is it possible to please provide an ARM build for Linux on Flathub?

I'd like to try Sly on a Librem 5 Linux phone as it looks like it will adapt perfectly to the small screen.

It should also benefit other Linux ARM devices like MNT Reform and Pocket, Tuxedo ARM laptops, Steam Deck, Raspberry Pi, Banana Pi, etc.

Thanks.

**Comment by kra-mo** [comment] 2024-10-03 14:04
Duplicate of #16

**Closed by kra-mo** 2024-10-03 14:04 UTC
